### ISSUE TITLE
Permission to use formatting in notes

### ISSUE THREAD

**Issue by Folas1337** [YingaGaming/Sign#1]
It would be nice to have an additional permission to prevent people from using formatting codes such as &f.

Something like `sign.notes.formatting` or if you want to be even more specific, `sign.notes.format.color`, `sign.notes.format.special` and whatever else you can think of.

Since you could make lore look just like an enchantment, it could be used in various malicious ways and I'd like to prevent that.

Alternatively there could be a custom prefix for notes, so any note would always start with something like `Lore: `

Personally I like the custom prefix better so it's more obvious and people can still use colors but once again, all these decisions I'll make up to you :)

**Comment by xenorio** [comment]
Oh hey, I didn't even know this thing is actually being used somewhere else :)

Actually, both of those ideas aren't bad. I think I'll look into implementing both of them, just to provide more options.

However, this is gonna take like 2-3 weeks, since I currently have some private matters to attend to and can't allow myself to get distracted with coding shenanigans right now.

**Comment by Folas1337** [comment]
Oh hey, I didn't even know you were still maintaining this :)
In all honesty, it's a good plugin and does it in a way I haven't found in any other free (and especially open-source) plugins, so keep it up, it's awesome!

Also it's completely fine if it takes you a little while, I'll also be away for the next couple days so it's entirely fine :)

**Comment by xenorio** [comment]
Implemented in [1.1.0](https://github.com/YingaGaming/Sign/releases/tag/v1.1.0) 😄
